### ISSUE TITLE
A patch suggestion

### ISSUE THREAD

**Issue by george1502** [Llandon/lsmount#1]
I had problems to get the program built on my Ubuntu. After a bit of searching it worked as I made this little changes. I tried to upload my version, but I got a 403Error. SI raised an issue and posted it this way.

diff --git a/Makefile b/Makefile
index 4c3e380..9dea06b 100644
--- a/Makefile
+++ b/Makefile
@@ -15,7 +15,7 @@ debug: CFLAGS += -g -Og -DDEBUG -Wextra -pedantic  -Wcast-qual -Wcast-align -Wfo
 debug: $(BIN)

 lsmount:   lsmount.o lsmgrid.o options.o
-   $(CC) $(LDLIBS) -o $@ $(OBJ)
-   $(CC) -o $@ $(OBJ) $(LDLIBS)
  lsmount.o: lsmount.c lsmount.h ansicodes.h
    $(CC) $(CFLAGS) -c -o $@ $<
  lsmgrid.o: lsmgrid.c lsmgrid.h
  diff --git a/src/options.c b/src/options.c
  index fb4e330..d960405 100644
  --- a/src/options.c
  +++ b/src/options.c
  @@ -126,8 +126,8 @@ int readconffile(const char\* config_file) {
  
   if (!config_read_file(&cfg, config_file)) {
       printf(
-            _("Can't read config-file %s:%d - %s\n"), 
-            config_error_file(&cfg), 
-            _("Can't read config-file %s: %d - %s\n"), 
-            config_file, 
           config_error_line(&cfg), 
           config_error_text(&cfg)
       );

**Comment by Llandon** [comment]
shoul be fixed in 255522e
